### ISSUE TITLE
Ao compartilhar post no Facebook a imagem incorreta é exibida

### ISSUE THREAD

**Issue by wlsf82** [TallerWebSolutions/blog#101]
Mesmo estando configurada a imagem que será exibida quando se faz o compartilhamento das redes sociais, quando compartilho posts do blog no Facebook, ele exibe a foto do autor, em vez da imagem do post.

**Comment by deivamagalhaes** [comment]
Uau, 2015... faz uns dias aí!

**Comment by panchiniak** [comment]
Somente o "unsubscripe" poderah nos salvar. Unsubscribeee!? :) :*
