### ISSUE TITLE
Listagem de posts sobrescreve rodapé

### ISSUE THREAD

**Issue by marigraf** [TallerWebSolutions/blog#34]
No fim da página às vezes acontece um bug que continua o texto por cima do rodapé. Segue print:

![image](https://cloud.githubusercontent.com/assets/7515326/6306724/eaedab88-b91c-11e4-8d33-e0bf6a1eabb1.png)

**Comment by marigraf** [comment]
Navegador Chrome Versão 40.0.2214.115 m

**Comment by gneutzling** [comment]
Mari, você ainda consegue reproduzir esse bug? Tentei, mas ainda não rolou aqui.

**Comment by gneutzling** [comment]
Quando as imagens demoram para carregar o bug ainda está acontecendo.
