### ISSUE TITLE
Larguras divergentes na página de post

### ISSUE THREAD

**Issue by lucasconstantino** [TallerWebSolutions/blog#38]
O corpo do post possui uma largura reduzida planejada para facilitar a leitura. Essa largura é baseada no tamanho da fonte de cada componente do corpo. Por consequência, elementos com tamanho de fonte maior (títulos, pro exemplo) possuem larguras superiores às dos outros elementos, o que causa diversas larguras divergentes durante o conteúdo do post.

**Comment by rafaelcaceres** [comment]
Como resolvemos, fixando uma largura?

**Comment by lhguerra** [comment]
Eu deixei isso assim propositalmente, pra não limitar elementos maiores à largura dos blocos de texto. E foi como foi apresentado inclusive.

Acho que teria que ser feita uma análise sobre qual abordagem utilizar para essa diagramação caso alguma mudança se faça necessária.

**Comment by italomen** [comment]
Então, acredito que pequenos ajustes já melhoram bastante:

.post-content { max-width: 35em;

Passar de 30 para 35 dá um pouco mais de espaço para o texto.

Recuando um pouco os subtítulos a composição fica boa para leitura:

![screen shot 2015-03-05 at 18 36 54](https://cloud.githubusercontent.com/assets/8739899/6515202/b05d9c54-c366-11e4-8492-3f1c106fce6a.png)

Notem que a parte antes da ilustração está com a coluna mais larga. Esse é o efeito de aumentar o max-width.

**Comment by lhguerra** [comment]
@italomen 

A coluna tem essa largura por um motivo. Segue uma largura considerada idel para leitura de acordo com o tamanho da fonte, mantendo uma média de caracteres por linha entre 60 e 70, segundo estudo de Robert Bringhurst.

A referência é a tabela abaixo (as unidades físicas foram convertidas em digitais, assim 1pt equivale a 1px e 1p equivale a 12px, mantendo a proporção). Apesar de estarem previstos valores considerados satisfatórios, é altamente recomendado que se mantenha a largura ideal sempre que possível.

![tabela_bringhurst](https://cloud.githubusercontent.com/assets/4529663/6529910/288c51f8-c40b-11e4-9f66-e0f9ed468e7e.jpg)

Eu proporia padronizar a largura dos elementos de texto que não são parágrafos (para diminuir a divergência que o @lucasconstantino observou), mantendo ou não um recuo (eu ainda acho interessante manter, como o @italomen propôs), e deixaria livre pra outros elementos, como código e imagens.

Ademais, esse tópico já está merecendo uma reunião. Se concordarem, vamos pra outro canal e marcamos isso.

**Comment by lhguerra** [comment]
Tarefas definidas:

 - Remover social media icons do topo.
 - Definir largura de coluna do destaque como padrão expandido para elementos de texto que não sejam os parágrafos.
 - Testar imagens e códigos das duas formas (com a largura padrão e estourando).
 - Testar largura dos parágrafos entre 32 e 33em.
