### ISSUE TITLE
Lista parece estar alinhado a esquerda

### ISSUE THREAD

**Issue by sebas5384** [TallerWebSolutions/blog#67]
Estou usando Chrome no Mac

**Comment by rafaelcaceres** [comment]
pode explicar melhor? botar um screenshot se possivel...

**Comment by lhguerra** [comment]
Isso?

http://awesomescreenshot.com/0e34jknt60

**Comment by sebas5384** [comment]
é isso mesmo @lhguerra, valeu!

**Comment by rafaelcaceres** [comment]
o screenshot nao tá rolando mais! é a lista da home? agora que vi que tah alinhada mesmo

**Comment by gneutzling** [comment]
Isso acontece por que o masonry está esperando as imagens serem carregadas. Tentei ajustar colocando um breakpoint e voltando o alinhamento ao centro.
