### ISSUE TITLE
Links externos estão abrindo na mesma aba/janela

### ISSUE THREAD

**Issue by lhguerra** [TallerWebSolutions/blog#7]
Como os posts são feitos por markdown, uma solução deve ser encontrada para adicionar o target automaticamente em links externos.

**Comment by gneutzling** [comment]
Atualmente os links externos estão abrindo em uma nova aba. It's magic xD

Concordam em abrir uma nova issue para o refactoring do handlebar-helpers.js?

**Comment by gneutzling** [comment]
Coloquei essa issue pra done pois os links já estão abrindo em uma nova aba e considero que refactoring deve ser constante, não precisando de um card específico.
