### ISSUE TITLE
Upgrade na área do autor e no pós-texto

### ISSUE THREAD

**Issue by italomen** [TallerWebSolutions/blog#76]
Dei uma simplicada e refinada na parte final do blog. O que acham:

![screen shot 2015-03-05 at 18 23 00](https://cloud.githubusercontent.com/assets/8739899/6515022/a7ec3360-c365-11e4-8f3d-5d18deeccf77.png)

**Comment by italomen** [comment]
A idea é colocar as labels para baixo e os botões de compartilhamento também, até por que é no final do texto que a gente decide se quer compartilhar.

**Comment by italomen** [comment]
Uma outra possibilidade é essa:

![screen shot 2015-03-05 at 19 08 42](https://cloud.githubusercontent.com/assets/8739899/6515735/12633716-c36b-11e4-99f2-2ecc3e620844.png)

**Comment by lhguerra** [comment]
Achei ótimo. Se ninguém tiver objeção vou começar a trabalhar nisso Segunda-feira.

**Comment by lucasconstantino** [comment]
@italomen muito bom mesmo. Concordo com todas as mudanças.
