### ISSUE TITLE
Utilizar branch DEV e MASTER

### ISSUE THREAD

**Issue by sebas5384** [TallerWebSolutions/blog#83]
## dev
Tudo aqui pode ser considerado instável e não testado.

## master
Considerado estável e testado. Nada que esteja "work in progress" pode estar aqui.

**Comment by gneutzling** [comment]
Já trabalhamos com uma branch dev que faz deploy em homolog-blog.taller.net.br
A branch master vai direto para o blog em produção.

De qualquer maneira acho válido essas observações estarem no readme.md

**Comment by gneutzling** [comment]
Atualizei o readme para facilitar a instalação de quem for trabalhar no projeto e para não haver dúvidas com relação as branches. https://github.com/TallerWebSolutions/blog/blob/master/README.md
