### ISSUE TITLE
Página de autor mostra todos os posts

### ISSUE THREAD

**Issue by lhguerra** [TallerWebSolutions/blog#88]
Como os artigos são postados por apenas uma conta, as páginas dos autores não filtram os artigos pelo autor.

Possíveis abordagens:
 - Remover o link do nome do autor onde aparece.
 - Procurar uma forma de filtrar os posts sem precisar criar uma conta para cada um que publica.

**Comment by gneutzling** [comment]
Em um primeiro momento optei por remover o link.
