### ISSUE TITLE
Corrigir menções no site da Taller

### ISSUE THREAD

**Issue by lucasconstantino** [TallerWebSolutions/blog#9]
O [site da Taller](http://taller.net.br) não foi atualizado nos locais on linka ao blog da Taller, estando ainda apontando para [Drupal de Elite](http://drupaldeelite.com.br). Também deve ser alterado o consumo de RSS para ou passar a exibir somente feeds do blog da Taller ou passar a exibir de ambos.

**Comment by rafaelcaceres** [comment]
Testei e tá funcionando os links. Aparentemente ele pega do drupal de elite e do blog da taller.

Um problema era que a cron não tava configurada no drupal, ai não importava automaticamente.
